language = "Mercury"
display = "Mercury (Mercury 22.01.8)"
filename = "main.m"
object = "a.out"
compile = """
mmc -o a.out -O 5 main
"""
execution = ["./a.out"]
install = """
sudo apt update
sudo apt-get install -y wget ca-certificates
cd /tmp
wget https://paul.bone.id.au/paul.asc
sudo cp paul.asc /etc/apt/trusted.gpg.d/paulbone.asc
echo \"deb http://dl.mercurylang.org/deb/ noble main\" | sudo tee /etc/apt/sources.list.d/mercury.list
echo \"deb-src http://dl.mercurylang.org/deb/ noble main\" | sudo tee -a /etc/apt/sources.list.d/mercury.list
sudo apt update
sudo apt-get install -y mercury-recommended
"""

[[license]]
name = "GPL-2.0-only"
url = "https://www.mercurylang.org/download/COPYING"

[[license]]
name = "!License-15"
url = "https://www.mercurylang.org/download/COPYING.LIB"
