language = "R"
display = "R (GNU R 4.5.0)"
filename = "Main.R"
object = "a.out"
compile = """
Rscript Main.R < /dev/null &> /dev/null
Rscript -e \"parse('Main.R')\" && touch a.out
"""
execution = [
  "Rscript",
  "Main.R",
]
install = """
# ***** R 4.5.0をバージョン指定してインストール *****
# 作業フォルダ作成
mkdir /tmp/r-install
cd /tmp/r-install
# wgetインストール
sudo apt install -y wget
# ソフトウェアファイルをダウンロード
wget https://cloud.r-project.org/bin/linux/ubuntu/noble-cran40/r-base-core_4.5.0-3.2404.0_amd64.deb
wget https://cloud.r-project.org/bin/linux/ubuntu/noble-cran40/r-recommended_4.5.0-3.2404.0_all.deb
wget https://cloud.r-project.org/bin/linux/ubuntu/noble-cran40/r-base_4.5.0-3.2404.0_all.deb
wget https://cloud.r-project.org/bin/linux/ubuntu/noble-cran40/r-base-dev_4.5.0-3.2404.0_all.deb
# ソフトウェアをインストール
sudo apt install -y ./r-base-core_4.5.0-3.2404.0_amd64.deb
sudo apt install -y ./r-recommended_4.5.0-3.2404.0_all.deb
sudo apt install -y ./r-base_4.5.0-3.2404.0_all.deb
sudo apt install -y ./r-base-dev_4.5.0-3.2404.0_all.deb
# 作業フォルダ削除
cd ../
rm -r r-install

# ***** パッケージをバージョン指定してインストール *****
# パッケージ: bit64, collections, dplyr, e1071, gtools, lubridate, magrittr, purrr, Rcpp, readr, sets, stringr, zeallot
# バージョン指定するためソースファイルからインストールをするので、依存パッケージも手動でインストール必要
# バージョンは 2025年 4月 19日時点の最新
# ---
# パッケージを配列で定義（依存関係上、この順番でインストールする）
packages=(\"cli\" \"generics\" \"glue\" \"magrittr\" \"fansi\" \"utf8\" \"R6\" \"rlang\" \"pkgconfig\" \"withr\" \"lifecycle\" \"vctrs\" \"pillar\" \"tibble\" \"tidyselect\" \"dplyr\" \"proxy\" \"e1071\" \"gtools\" \"cpp11\" \"timechange\" \"lubridate\" \"purrr\" \"Rcpp\" \"clipr\" \"crayon\" \"hms\" \"bit\" \"bit64\" \"prettyunits\" \"progress\" \"tzdb\" \"vroom\" \"readr\" \"sets\" \"stringi\" \"stringr\" \"zeallot\" \"collections\")

# パッケージとバージョンの組を連想配列で定義
declare -A versions=(
    [\"cli\"]=\"3.6.4\"
    [\"generics\"]=\"0.1.3\"
    [\"glue\"]=\"1.8.0\"
    [\"magrittr\"]=\"2.0.3\"
    [\"fansi\"]=\"1.0.6\"
    [\"utf8\"]=\"1.2.4\"
    [\"R6\"]=\"2.6.1\"
    [\"rlang\"]=\"1.1.6\"
    [\"pkgconfig\"]=\"2.0.3\"
    [\"withr\"]=\"3.0.2\"
    [\"lifecycle\"]=\"1.0.4\"
    [\"vctrs\"]=\"0.6.5\"
    [\"pillar\"]=\"1.10.2\"
    [\"tibble\"]=\"3.2.1\"
    [\"tidyselect\"]=\"1.2.1\"
    [\"dplyr\"]=\"1.1.4\"
    [\"proxy\"]=\"0.4-27\"
    [\"e1071\"]=\"1.7-16\"
    [\"gtools\"]=\"3.9.5\"
    [\"cpp11\"]=\"0.5.2\"
    [\"timechange\"]=\"0.3.0\"
    [\"lubridate\"]=\"1.9.4\"
    [\"purrr\"]=\"1.0.4\"
    [\"Rcpp\"]=\"1.0.14\"
    [\"clipr\"]=\"0.8.0\"
    [\"crayon\"]=\"1.5.3\"
    [\"hms\"]=\"1.1.3\"
    [\"bit\"]=\"4.6.0\"
    [\"bit64\"]=\"4.6.0-1\"
    [\"prettyunits\"]=\"1.2.0\"
    [\"progress\"]=\"1.2.3\"
    [\"tzdb\"]=\"0.5.0\"
    [\"vroom\"]=\"1.6.5\"
    [\"readr\"]=\"2.1.5\"
    [\"sets\"]=\"1.0-25\"
    [\"stringi\"]=\"1.8.7\"
    [\"stringr\"]=\"1.5.1\"
    [\"zeallot\"]=\"0.1.0\"
    [\"collections\"]=\"0.3.7\"
)

# 各パッケージを処理
for PACKAGE in \"${packages[@]}\"; do
    VERSION=${versions[$PACKAGE]}

    # Rを使ってURLを判定
    URL=$(Rscript -e \"
        latest_info <- available.packages();
        if ('$PACKAGE' %in% rownames(latest_info)) {
            latest_version <- latest_info['$PACKAGE', 'Version']
            if ('$VERSION' == latest_version) {
                cat('https://cran.r-project.org/src/contrib/', '$PACKAGE', '_', '$VERSION', '.tar.gz', sep='')
            } else {
                cat('https://cran.r-project.org/src/contrib/Archive/', '$PACKAGE', '/', '$PACKAGE', '_', '$VERSION', '.tar.gz', sep='')
            }
        } else {
            stop('Package not found in available CRAN packages.')
        }
    \" 2>/dev/null)

    # エラー処理
    if [ $? -ne 0 ]; then
        echo \"Error: Could not determine the URL for the package ${PACKAGE} version ${VERSION}.\"
        continue
    fi

    # パッケージをインストール
    echo \"Installing ${PACKAGE} version ${VERSION} from ${URL}\"
    sudo Rscript -e \"install.packages('${URL}', repos=NULL, type='source', ask=FALSE)\"
done
"""

[[license]]
name = "AGPL-3.0-only"
url = "https://www.r-project.org/Licenses/AGPL-3"

[[license]]
name = "Artistic-2.0"
url = "https://www.r-project.org/Licenses/Artistic-2.0"

[[license]]
name = "BSD-2-Clause"
url = "https://www.r-project.org/Licenses/BSD_2_clause"

[[license]]
name = "BSD-3-Clause"
url = "https://www.r-project.org/Licenses/BSD_3_clause"

[[license]]
name = "GPL-2.0-only"
url = "https://www.r-project.org/Licenses/GPL-2"

[[license]]
name = "GPL-3.0-only"
url = "https://www.r-project.org/Licenses/GPL-3"

[[license]]
name = "LGPL-2.0-only"
url = "https://www.r-project.org/Licenses/LGPL-2"

[[license]]
name = "LGPL-2.1-only"
url = "https://www.r-project.org/Licenses/LGPL-2.1"

[[license]]
name = "LGPL-3.0-only"
url = "https://www.r-project.org/Licenses/LGPL-3"

[[license]]
name = "MIT"
url = "https://www.r-project.org/Licenses/MIT"

[[license]]
name = "CC-BY-SA-4.0"
url = "https://www.r-project.org/Licenses/CC-BY-SA-4.0"

[library.cli]
version = "3.6.4"
indirect = true

[[library.cli.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.generics]
version = "0.1.3"
indirect = true

[[library.generics.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.glue]
version = "1.8.0"
indirect = true

[[library.glue.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.magrittr]
version = "2.0.3"
indirect = false

[[library.magrittr.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.fansi]
version = "1.0.6"
indirect = true

[[library.fansi.license]]
name = "GPL-2.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[[library.fansi.license]]
name = "GPL-3.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-3"

[library.utf8]
version = "1.2.4"
indirect = true

[[library.utf8.license]]
name = "Apache-2.0"
url = "https://cran.r-project.org/web/packages/utf8/LICENSE"

[library.R6]
version = "2.6.1"
indirect = true

[[library.R6.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.rlang]
version = "1.1.6"
indirect = true

[[library.rlang.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.pkgconfig]
version = "2.0.3"
indirect = true

[[library.pkgconfig.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.withr]
version = "3.0.2"
indirect = true

[[library.withr.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.lifecycle]
version = "1.0.4"
indirect = true

[[library.lifecycle.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.vctrs]
version = "0.6.5"
indirect = true

[[library.vctrs.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.pillar]
version = "1.10.2"
indirect = true

[[library.pillar.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.tibble]
version = "3.2.1"
indirect = true

[[library.tibble.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.tidyselect]
version = "1.2.1"
indirect = true

[[library.tidyselect.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.dplyr]
version = "1.1.4"
indirect = false

[[library.dplyr.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.proxy]
version = "0.4-27"
indirect = true

[[library.proxy.license]]
name = "GPL-2.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[library.e1071]
version = "1.7-16"
indirect = false

[[library.e1071.license]]
name = "GPL-2.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[[library.e1071.license]]
name = "GPL-3.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-3"

[library.gtools]
version = "3.9.5"
indirect = false

[[library.gtools.license]]
name = "GPL-2.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[library.cpp11]
version = "0.5.2"
indirect = true

[[library.cpp11.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.timechange]
version = "0.3.0"
indirect = true

[[library.timechange.license]]
name = "GPL-3.0-or-later"
url = "https://cran.r-project.org/web/licenses/GPL-3"

[library.lubridate]
version = "1.9.4"
indirect = false

[[library.lubridate.license]]
name = "GPL-2.0-or-later"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[[library.lubridate.license]]
name = "GPL-3.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-3"

[library.purrr]
version = "1.0.4"
indirect = false

[[library.purrr.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.Rcpp]
version = "1.0.14"
indirect = false

[[library.Rcpp.license]]
name = "GPL-2.0-or-later"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[[library.Rcpp.license]]
name = "GPL-3.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-3"

[library.clipr]
version = "0.8.0"
indirect = true

[[library.clipr.license]]
name = "GPL-3.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-3"

[library.crayon]
version = "1.5.3"
indirect = true

[[library.crayon.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.hms]
version = "1.1.3"
indirect = true

[[library.hms.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.bit]
version = "4.6.0"
indirect = true

[[library.bit.license]]
name = "GPL-2.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[[library.bit.license]]
name = "GPL-3.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-3"

[library.bit64]
version = "4.6.0-1"
indirect = false

[[library.bit64.license]]
name = "GPL-2.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[[library.bit64.license]]
name = "GPL-3.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-3"

[library.prettyunits]
version = "1.2.0"
indirect = true

[[library.prettyunits.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.progress]
version = "1.2.3"
indirect = true

[[library.progress.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.tzdb]
version = "0.5.0"
indirect = true

[[library.tzdb.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.vroom]
version = "1.6.5"
indirect = true

[[library.vroom.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.readr]
version = "2.1.5"
indirect = false

[[library.readr.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.sets]
version = "1.0-25"
indirect = false

[[library.sets.license]]
name = "GPL-2.0-only"
url = "https://cran.r-project.org/web/licenses/GPL-2"

[library.stringi]
version = "1.8.7"
indirect = true

[[library.stringi.license]]
name = "BSD-2-Clause"
url = "https://cran.r-project.org/web/packages/stringi/LICENSE"

[[library.stringi.license]]
name = "BSD-3-Clause"
url = "https://cran.r-project.org/web/packages/stringi/LICENSE"

[[library.stringi.license]]
name = "GPL-2.0-or-later"
url = "https://cran.r-project.org/web/packages/stringi/LICENSE"

[[library.stringi.license]]
name = "ICU"
url = "https://cran.r-project.org/web/packages/stringi/LICENSE"

[[library.stringi.license]]
name = "NAIST-2003"
url = "https://cran.r-project.org/web/packages/stringi/LICENSE"

[[library.stringi.license]]
name = "Unicode-3.0"
url = "https://cran.r-project.org/web/packages/stringi/LICENSE"

[library.stringr]
version = "1.5.1"
indirect = false

[[library.stringr.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.zeallot]
version = "0.1.0"
indirect = false

[[library.zeallot.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"

[library.collections]
version = "0.3.7"
indirect = false

[[library.collections.license]]
name = "MIT"
url = "https://cran.r-project.org/web/licenses/MIT"
