language = "SageMath"
display = "SageMath (SageMath 10.7)"
filename = "Main.sage"
object = "Main.sage.py"
compile = """
sage --preparse Main.sage
python3 -m py_compile Main.sage.py || rm Main.sage.py
"""
execution = [
  "sage",
  "--python3",
  "Main.sage.py",
]
install = """
cd /tmp
sudo apt update

# Reference: https://sagemanifolds.obspm.fr/install_ubuntu.html
sudo apt install -y automake bc binutils bzip2 ca-certificates cliquer cmake curl ecl eclib-tools fflas-ffpack flintqs g++ gengetopt gfan gfortran git glpk-utils gmp-ecm lcalc libatomic-ops-dev libboost-dev libbraiding-dev libbz2-dev libcdd-dev libcdd-tools libcliquer-dev libcurl4-openssl-dev libec-dev libecm-dev libffi-dev libflint-dev libfreetype-dev libgc-dev libgd-dev libgf2x-dev libgiac-dev libgivaro-dev libglpk-dev libgmp-dev libgsl-dev libhomfly-dev libiml-dev liblfunction-dev liblrcalc-dev liblzma-dev libm4rie-dev libmpc-dev libmpfi-dev libmpfr-dev libncurses-dev libntl-dev libopenblas-dev libpari-dev libpcre3-dev libplanarity-dev libppl-dev libprimecount-dev libprimesieve-dev libpython3-dev libqhull-dev libreadline-dev librw-dev libsingular4-dev libsqlite3-dev libssl-dev libsuitesparse-dev libsymmetrica2-dev zlib1g-dev libzmq3-dev libzn-poly-dev m4 make nauty openssl palp pari-doc pari-elldata pari-galdata pari-galpol pari-gp2c pari-seadata patch perl pkg-config planarity ppl-dev python3-setuptools python3-venv r-base-dev r-cran-lattice singular sqlite3 sympow tachyon tar tox xcas xz-utils
git clone --branch 10.7 --depth 1 https://github.com/sagemath/sage.git
cd sage
make configure
./configure --prefix=$HOME/sage --disable-editable --enable-build-as-root
MAKE=\"make -j$(nproc --all)\" make
sudo ln -s $HOME/sage/bin/sage /usr/local/bin/sage
"""

[[license]]
name = "GPL-3.0-only"
url = "https://github.com/sagemath/sage/blob/10.7/COPYING.txt"
